# Generated by Django 5.2.7 on 2025-11-04 15:54

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('ACCOUNT_CREATED', 'Account Created'), ('APPLICATION_SUBMITTED', 'Application Submitted'), ('APPLICATION_STATUS_CHANGED', 'Application Status Changed'), ('NEW_MESSAGE', 'New Message'), ('JOB_MATCH', 'Job Match'), ('PASSWORD_RESET', 'Password Reset'), ('PAYMENT_REMINDER', 'Payment Reminder')], db_index=True, max_length=50)),
                ('channel', models.CharField(choices=[('EMAIL', 'Email'), ('WHATSAPP', 'WhatsApp'), ('IN_APP', 'In-App')], max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('data', models.JSONField(blank=True, default=dict)),
                ('read', models.BooleanField(db_index=True, default=False)),
                ('sent', models.BooleanField(default=False)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'db_table': 'notifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
