# Generated by Django 5.2.7 on 2025-11-04 15:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applications', '0001_initial'),
        ('jobs', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='users.candidate'),
        ),
        migrations.AddField(
            model_name='application',
            name='job_offer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='jobs.joboffer'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['candidate'], name='application_candida_0452de_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['job_offer'], name='application_job_off_5e8367_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['status'], name='application_status_e61111_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['-match_score'], name='application_match_s_48d9cf_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['-applied_at'], name='application_applied_f50165_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='application',
            unique_together={('candidate', 'job_offer')},
        ),
    ]
