# Generated by Django 5.2.7 on 2025-11-04 15:54

import django.contrib.postgres.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobOffer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(db_index=True, max_length=255)),
                ('description', models.TextField()),
                ('requirements', models.TextField(blank=True, null=True)),
                ('responsibilities', models.TextField(blank=True, null=True)),
                ('salary_min', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('salary_max', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('salary_currency', models.CharField(default='XOF', max_length=3)),
                ('salary_period', models.CharField(blank=True, choices=[('HOURLY', 'Per Hour'), ('MONTHLY', 'Per Month'), ('YEARLY', 'Per Year')], max_length=20, null=True)),
                ('contract_type', models.CharField(choices=[('CDI', 'CDI - Permanent Contract'), ('CDD', 'CDD - Fixed-term Contract'), ('FREELANCE', 'Freelance'), ('INTERNSHIP', 'Internship'), ('APPRENTICESHIP', 'Apprenticeship')], max_length=50)),
                ('location', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('is_remote', models.BooleanField(default=False)),
                ('skills_required', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, size=None)),
                ('experience_level', models.CharField(blank=True, choices=[('JUNIOR', 'Junior (0-2 years)'), ('INTERMEDIATE', 'Intermediate (2-5 years)'), ('SENIOR', 'Senior (5-10 years)'), ('EXPERT', 'Expert (10+ years)')], max_length=50, null=True)),
                ('education_required', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published'), ('CLOSED', 'Closed'), ('ARCHIVED', 'Archived'), ('REJECTED', 'Rejected')], db_index=True, default='DRAFT', max_length=20)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('views_count', models.IntegerField(default=0)),
                ('applications_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'job_offers',
                'ordering': ['-published_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SavedJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('saved_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'saved_jobs',
                'ordering': ['-saved_at'],
            },
        ),
    ]
