# Generated by Django 5.2.7 on 2025-11-04 15:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='joboffer',
            name='recruiter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_offers', to='users.recruiter'),
        ),
        migrations.AddField(
            model_name='savedjob',
            name='candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_jobs', to='users.candidate'),
        ),
        migrations.AddField(
            model_name='savedjob',
            name='job_offer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_by', to='jobs.joboffer'),
        ),
        migrations.AddIndex(
            model_name='joboffer',
            index=models.Index(fields=['recruiter'], name='job_offers_recruit_204dfe_idx'),
        ),
        migrations.AddIndex(
            model_name='joboffer',
            index=models.Index(fields=['status'], name='job_offers_status_d5a63d_idx'),
        ),
        migrations.AddIndex(
            model_name='joboffer',
            index=models.Index(fields=['location'], name='job_offers_locatio_c49aeb_idx'),
        ),
        migrations.AddIndex(
            model_name='joboffer',
            index=models.Index(fields=['contract_type'], name='job_offers_contrac_fefe3a_idx'),
        ),
        migrations.AddIndex(
            model_name='joboffer',
            index=models.Index(fields=['published_at'], name='job_offers_publish_0b3d93_idx'),
        ),
        migrations.AddIndex(
            model_name='savedjob',
            index=models.Index(fields=['candidate'], name='saved_jobs_candida_94e28e_idx'),
        ),
        migrations.AddIndex(
            model_name='savedjob',
            index=models.Index(fields=['job_offer'], name='saved_jobs_job_off_5890b2_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='savedjob',
            unique_together={('candidate', 'job_offer')},
        ),
    ]
